---
title: "Google Mobility 04-11"
author: "Thomas Li"
date: "4/11/2021"
output: pdf_document
---
```{r}
library(pacman)
p_load(readr,COVID19,leaps,ggplot2,tidyverse,dplyr,car)
```


```{r message=FALSE}
# region mobility report
region_mobility21 <- read_csv("2021_US_Region_Mobility_Report.csv")
region_mobility20 <- read_csv("2020_US_Region_Mobility_Report.csv")
region_mobility20.21 <- merge(x = region_mobility20, y = region_mobility21, all = T)
```

Subsetting Google Mobility data to for linear regression model
```{r}
# subset dataframe range to CA only
ca_mobility20.21 <- region_mobility20.21 %>% 
  filter(sub_region_1 == "California", date >= "2020-03-15", date <= "2021-03-15")

# remove unique identifier columns
ca_mobility.col <- ca_mobility20.21[,-c(5:8)]

# remove N/A
ca_mobility.omit <- na.omit(ca_mobility.col)

# convert percentages to decimals
ca_mobility.dat <- ca_mobility.omit[,6:11]/100
```


```{r}
cacovid19data <- covid19("US", level = 2) %>% 
  filter(administrative_area_level_2 == "California", date >= "2020-03-15", date <= "2021-03-15")

base_data <- subset(cacovid19data, select = c("date", "confirmed", "deaths", "administrative_area_level_2", "latitude"  , "longitude", "population",  "school_closing", "workplace_closing", "gatherings_restrictions", "stay_home_restrictions", "internal_movement_restrictions", "information_campaigns", "testing_policy", "contact_tracing", "stringency_index"))
```


```{r}

fschool_closing = as.factor(base_data$school_closing)
fworkplace_closing <- as.factor(base_data$workplace_closing)
fgatherings_restrictions <- as.factor(base_data$gatherings_restrictions)
fstay_home_restrictions <- as.factor(base_data$stay_home_restrictions)
finternal_movement_restrictions <- as.factor(base_data$internal_movement_restrictions)
finformation_campaigns <- as.factor(base_data$information_campaigns)
ftesting_policy <- as.factor(base_data$testing_policy)
fcontact_tracing <- as.factor(base_data$contact_tracing)
```


```{r}
attach(base_data)


fbase_data <- base_data %>% 
  mutate(fschool_closing, fworkplace_closing, fgatherings_restrictions,
         fstay_home_restrictions, finternal_movement_restrictions,
         finformation_campaigns, ftesting_policy, fcontact_tracing)

head(fbase_data)

```



```{r}
# merge covid19 and google mobility data

cacovid_mobility <- merge(x = ca_mobility.dat, y = fbase_data, all = T)
head(cacovid_mobility)

```


```{r}
# full fitted model
google.full <- lm(deaths ~ retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + transit_stations_percent_change_from_baseline + workplaces_percent_change_from_baseline + residential_percent_change_from_baseline + date + confirmed + latitude  + longitude + population +  fschool_closing +
            fworkplace_closing + fgatherings_restrictions + fstay_home_restrictions + finternal_movement_restrictions  +
            finformation_campaigns + ftesting_policy + fcontact_tracing + stringency_index, data = cacovid_mobility)

pairs(google.full)

plot(google.full, which = c(1,2))

summary(cacovid_mobility)
google.covid <- lm(confirmed ~ ., data = cacovid_mobility)

plot(google.covid)
```


```{r}
google.full <- lm(deaths ~ retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + transit_stations_percent_change_from_baseline + workplaces_percent_change_from_baseline + residential_percent_change_from_baseline + date + confirmed + latitude  + longitude + population +  fschool_closing +
            fworkplace_closing + fgatherings_restrictions + fstay_home_restrictions + finternal_movement_restrictions  +
            finformation_campaigns + ftesting_policy + fcontact_tracing + stringency_index, data = cacovid_mobility)

pairs(google.full)
```



```{r}
# optimal lambda for response from full model
boxCox(google.full)

# log transformed response fitted model
google.log <- lm(log(confirmed) ~ retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + transit_stations_percent_change_from_baseline + workplaces_percent_change_from_baseline + residential_percent_change_from_baseline, data = cacovid_mobility)

# null model
google.red <- lm(confirmed ~ 1, data = cacovid_mobility)
boxCox(google.full)
plot(google.log)

step(google.full, scope = list(lower = google.red, upper = google.full))

subset.summary <- summary(regsubsets(confirmed ~ retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + transit_stations_percent_change_from_baseline + workplaces_percent_change_from_baseline + residential_percent_change_from_baseline, data = cacovid_mobility))

subset.summary

predict_one <- lm(confirmed ~ retail_and_recreation_percent_change_from_baseline, data = cacovid_mobility)

predict_two <- lm(confirmed ~ retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline, data = cacovid_mobility)

predict_three <- lm(confirmed ~ retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline, data = cacovid_mobility)

predict_four <- lm(confirmed ~ retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + transit_stations_percent_change_from_baseline, data = cacovid_mobility)

predict_five <- lm(confirmed ~ retail_and_recreation_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + transit_stations_percent_change_from_baseline + workplaces_percent_change_from_baseline, data = cacovid_mobility)

summary(predict_one)
summary(predict_two)
summary(predict_three)
summary(predict_four)
summary(predict_five)

AIC(predict_one)
AIC(predict_two)
AIC(predict_three)
AIC(predict_four)
AIC(predict_five)
AIC(google.full)

BIC(predict_one)
BIC(predict_two)
BIC(predict_three)
BIC(predict_four)
BIC(predict_five)
BIC(google.full)
BIC(google.full)

summary(predict_one)$adj.r.squared
summary(predict_two)$adj.r.squared
summary(predict_three)$adj.r.squared
summary(predict_four)$adj.r.squared
summary(predict_five)$adj.r.squared
summary(google.full)$adj.r.squared
summary(google.log)$adj.r.squared
```

```{r}
summary(google.full)
plot(google.full)
```


```{r}
# powerTransform and invTranPlot only work for positive values
# Yeo-Johnson boxCox works with negative values
summary(powerTransform(cbind(retail_and_recreation_percent_change_from_baseline + 
    grocery_and_pharmacy_percent_change_from_baseline + parks_percent_change_from_baseline + 
    transit_stations_percent_change_from_baseline + workplaces_percent_change_from_baseline + 
    residential_percent_change_from_baseline) ~ 1, merge.dat))
invTranPlot(merge.dat$confirmed ~ merge.dat$retail_and_recreation_percent_change_from_baseline, optimal = T)
```


```{r}
# datahub provided merge
gmr <- "https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv"
x   <- covid19(gmr = gmr)
```

