---
title: "Untitled"
output: github_document
---

#Base Data with World Bank imported, GDP, GDP growth, Hospital beds/1,000 ppl, Poverty= Poverty head count ratio at 1.90 a day(% of pop), CO2em: CO2 emissions (metric tons/capita), Air pollution: % Pop exposed to levels exceeding WHO guidelines, 
```{r}
library(pacman)
p_load(COVID19, car, tidyverse, ggplot2, dplyr, leaps, readr)

x <- covid19()
covid19<- covid19(level = 1, start = "2020-03-15", end = "2021-03-15",)
wb <- c("gdp" = "NY.GDP.MKTP.CD", "hosp_beds" = "SH.MED.BEDS.ZS","gdp_grow" = "NY.GDP.MKTP.KD.ZG","poverty" = "SI.POV.DDAY", "co2em" = "EN.ATM.CO2E.PC", "pollution" = "EN.ATM.PM25.MC.ZS")
wbdcovid  <- covid19(wb = wb)

wbdcovid
```
#Only variables from WB and Confirmed and Death

```{r}
wbcovdata<- subset(wbdcovid, select = c("date", "confirmed", "deaths", "iso_alpha_3", "administrative_area_level_1", "gdp", "gdp_grow", "hosp_beds", "poverty", "co2em", "pollution"))


fgpd<- as.integer(wbcovdata$gdp)
fgdp_grow<- as.integer(wbcovdata$gdp_grow)
fhosp_beds<- as.integer(wbcovdata$hosp_beds)
fpoverty<- as.integer(wbcovdata$poverty)
fco2em<- as.integer(wbcovdata$co2em)
fpollution<- as.integer(wbcovdata$pollution)

#wbcovdata$gdp %>% replace_na(0)
#wbcovdata$gdp_grow %>% replace_na(0)
#wbcovdata$hosp_beds %>% replace_na(0)
#wbcovdata$poverty %>% replace_na(0)
#wbcovdata$co2em %>% replace_na(0)
#wbcovdata$pollution %>% replace_na(0)

                       
cleandata <- na.omit(wbcovdata)
cleandata
```
Graphs to check for Normality and variance

```{r}
#economic<- lm(deaths ~ confirmed, gdp, gdp_grow, poverty, data= cleandata) # Economic
#airqual<- lm(deaths ~ co2em, pollution, data= wbcovdata) #Air Quality

#summary(economic)
#summary(airqual)
```

